# Generated by Django 5.1.2 on 2024-12-20 11:32

import conference_rooms_app.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'Email już zarejestrowany w bazie'}, max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Hasło')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=9, validators=[conference_rooms_app.validators.validate_phone], verbose_name='Numer telefonu')),
                ('status', models.SmallIntegerField(choices=[(1, 'Użytkownik'), (2, 'Pracownik')], default=1, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktywny')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superużytkownik')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie logowania')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dołączenia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
