# Generated by Django 5.1.2 on 2024-12-20 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Nazwa sali już zapisana w bazie'}, max_length=64, unique=True, verbose_name='Nazwa')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Pojemność')),
                ('is_projector', models.BooleanField(default=False, verbose_name='Projector')),
            ],
            options={
                'verbose_name': 'Sala konferencyjna',
                'verbose_name_plural': 'Sale konferencyjne',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data rezerwacji')),
                ('message', models.TextField(null=True, verbose_name='Uwagi')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Potwierdzenie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_rooms_app.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Rezerwacja sali',
                'verbose_name_plural': 'Rezerwacje sal',
                'ordering': ('-date',),
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReservationUniqueToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conference_rooms_app.reservation', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Token rezerwacji',
                'verbose_name_plural': 'Tokeny rezerwacji',
                'ordering': ('reservation',),
            },
        ),
        migrations.CreateModel(
            name='UserUniqueToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Token użytkownika',
                'verbose_name_plural': 'Tokeny użytkowników',
                'ordering': ('user',),
            },
        ),
    ]
